### ISSUE TITLE
Front page: chart appears interactive, nothing happens after click

### ISSUE THREAD

**Issue by wbazant** [EBIvariation/eva-web#56]
I was on your website's main page, http://www.ebi.ac.uk/eva/. I didn't really know what it was about and I started hovering around the graphs because they looked interesting and without too much text.

Then the pie slice acted interactive and the cursor changed position to pointer, I got excited so I clicked! Then I watched the slice go out and be exposed and I expected to drill down and be taken somewhere but nothing like that happened. I clicked on some more pies because it was fun but I learned nothing about EVA in the process.

Possibly this is not meant to happen and I exposed an error but there was nothing in the console apart from some debug logs noise. Otherwise, this issue proposes to make the charts slightly less interactive, they're super pretty (in fact they took my attention away from the text where you tell me what I can actually do on it) but they don't help the user discover how to use the website.

**Comment by tcezard** [comment]
I know this is an old issue but in case someone is listening:
This is not an error but the expected behaviour.  The interactivity of the pie charts is limited to what you described.
