### ISSUE TITLE
Update submission instructions page

### ISSUE THREAD

**Issue by cyenyxe** [EBIvariation/eva-web#90]
Recent investigation of helpdesk stats show that we have a high rate of bounce submitters (that ask one question about submitting and then never return) and submitters that try to archive files with terminal faults.

We could be able to address (even if partially) these issues by improving the submission instructions.

### Simplify page structure
Make the structure more visually appealing, replacing or enriching some of the text with pictures and diagrams. The goal is to make the submission steps very clear, so we reduce the number of helpdesk tickets from people who don't even know where to start from.

### Describe the data that the EVA accept
Highlight that we accept all types of variants from any species.

List the types of sequences that are suitable for archival and make very clear that they must be accessioned by INSDC. Provide instructions on how to submit to INSDC or links to existing ones.

### Link to tools that could help submitters
Some tools that we should include in this documentation are:

* VCF validation suite
* Conversion from PED to VCF format (PlinkSeq)
* Conversion from genotyping array to VCF format

### Provide more VCF examples
Many submitters don't have a bioinformatics background and don't know how to build a valid VCF. Provide some basic examples of what is valid and what is not.

Some users have also expressed a lack of understanding of the differences between the INFO and FORMAT columns.

### Add information about sample accessioning
How to describe samples in the submission template, link to existing BioSamples accessions, etc.

### Avoid directing people to helpdesk before doing some homework
There are several references to the helpdesk address before even beginning to describe the submission process. This may be causing that some people contact the service without even having read all the information available on the website.

**Comment by tcezard** [comment]
This was addressed in EVA-1153: Closing
