### ISSUE TITLE
Change alleles displayed in GA4GH beacon form to explicit allele strings

### ISSUE THREAD

**Issue by cyenyxe** [EBIvariation/eva-web#92]
The [GA4GH beacon form](https://www.ebi.ac.uk/eva/?GA4GH) allows to test an endpoint that checks if a variant exists or not in the database. Currently all the examples represent insertions and deletion, but none a SNP where one base is replaced by another, such as A>G. These examples must be modified to display different types of variants.

**Comment by tcezard** [comment]
Now tracked in EVA-2047: closing
